### PR TITLE
added docker

### PR DESCRIPTION
**Pull request by mmblack4**

### CODE REVIEW

**Comment by Paillat-dev** [comment]
Isn't data persistence missing here?

**Comment by mmblack4** [comment]
so for we are using using local storage as db, so it not problem

**Comment by Paillat-dev** [comment]
> so for we are using using local storage as db, so it not problem

I don't get you. The databases are stored somewhere, and thus a volume needs to be mounted into the docker container to keep data persistent *between updates*. Otherwise data will be ephemeral since it will be stored inside the container and be lost when it is recreated.  Or am I missing something?

**Comment by mmblack4** [comment]
yep your right i totally missed that, I'll update volume

**Comment by mmblack4** [comment]
> > so for we are using using local storage as db, so it not problem
> 
> I don't get you. The databases are stored somewhere, and thus a volume needs to be mounted into the docker container to keep data persistent _between updates_. Otherwise data will be ephemeral since it will be stored inside the container and be lost when it is recreated. Or am I missing something?

it fixed now

**Comment by Paillat-dev** [comment]
@mmblack4 Nice. I did not testit, did you? From what I see, the volume is mounted at the same place as where the code is copied to in the Dockerfile (`/app`), but since a volume is added, the volume will override the actual code of the app and the container will crash. Instead, either the databases should be moved in another directory in the code and that directory mounted, or the database files should be mounted. See https://www.baeldung.com/ops/docker-mount-single-file-in-volume

**Comment by mmblack4** [comment]
if we add db in .dockerignore, it won't db file into image then only code will be update right!
```
notes.txt
data.db
esp.db
settings.db
```

**Comment by Paillat-dev** [comment]
Well, of course it will not be copied, but it will not be synchronized with the container, the databases will be stored into the container and not into the host.

**Comment by mmblack4** [comment]
"stored into the container" you mean volume, db stored inside volume only
```
    volumes:
      - mimosa_data:/app
```
"mimosa_data" can change into your system path
example:
```
    volumes:
      - user/root/app:/app
```

**Comment by Paillat-dev** [comment]
> "stored into the container" you mean volume, db stored inside volume only
> ```
>     volumes:
>       - mimosa_data:/app
> ```
> "mimosa_data" can change into your system path
> example:
> ```
>     volumes:
>       - user/root/app:/app
> ```

What I mean is that in this case the mimosa_data volume will OVERRIDE the /app directory in the container which is precisely where the code is. The volume(s) should only bind the database files or else the actual whole `/app` content will be the container

**Pull request closed without merging**
