### PR TITLE
Settings, ESP add_form and individual segment sizes added

### PR DESCRIPTION
**Pull request by JustReit**
added Settings Menu to change Brightness and turn off all LEDS, also added an add ESP form to select the ip and segment size ( also works with rational numbers if the number of LEDS and the number of rows don't match) of each ESP. Also changed the edit item function to populate the add item form for faster and easier editing

### CODE REVIEW

**Comment by FireMarshmellow** [comment]
Hey this is really nice work, I really like the party button!
Unfortunately the locate button doesn't seem to work.
It spits out this error:
`Traceback (most recent call last):
  File "c:\Users\tomas\Documents\GitHub\M.I.M.O.S.A\.venv\Lib\site-packages\flask\app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tomas\Documents\GitHub\M.I.M.O.S.A\.venv\Lib\site-packages\flask\app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tomas\Documents\GitHub\M.I.M.O.S.A\.venv\Lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tomas\Documents\GitHub\M.I.M.O.S.A\.venv\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tomas\Documents\GitHub\M.I.M.O.S.A\.venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\tomas\Documents\GitHub\M.I.M.O.S.A\.venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tomas\Documents\GitHub\M.I.M.O.S.A\app.py", line 135, in item
    lights(item['position'], item['ip'], empty=False)  # Call the 'lights' function without turning the LEDs red
  File "C:\Users\tomas\Documents\GitHub\M.I.M.O.S.A\app.py", line 172, in lights
    start_num= round(int((position - 1) * app.segment_size))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for -: 'str' and 'int'`

**Comment by JustReit** [comment]
> Hey this is really nice work, I really like the party button! Unfortunately the locate button doesn't seem to work. It spits out this error: `Traceback (most recent call last): File "c:\Users\tomas\Documents\GitHub\M.I.M.O.S.A\.venv\Lib\site-packages\flask\app.py", line 2551, in __call__ return self.wsgi_app(environ, start_response) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "c:\Users\tomas\Documents\GitHub\M.I.M.O.S.A\.venv\Lib\site-packages\flask\app.py", line 2531, in wsgi_app response = self.handle_exception(e) ^^^^^^^^^^^^^^^^^^^^^^^^ File "c:\Users\tomas\Documents\GitHub\M.I.M.O.S.A\.venv\Lib\site-packages\flask\app.py", line 2528, in wsgi_app response = self.full_dispatch_request() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "c:\Users\tomas\Documents\GitHub\M.I.M.O.S.A\.venv\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request rv = self.handle_user_exception(e) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "c:\Users\tomas\Documents\GitHub\M.I.M.O.S.A\.venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request rv = self.dispatch_request() ^^^^^^^^^^^^^^^^^^^^^^^ File "c:\Users\tomas\Documents\GitHub\M.I.M.O.S.A\.venv\Lib\site-packages\flask\app.py", line 1799, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\tomas\Documents\GitHub\M.I.M.O.S.A\app.py", line 135, in item lights(item['position'], item['ip'], empty=False) # Call the 'lights' function without turning the LEDs red File "C:\Users\tomas\Documents\GitHub\M.I.M.O.S.A\app.py", line 172, in lights start_num= round(int((position - 1) * app.segment_size)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: unsupported operand type(s) for -: 'str' and 'int'`

I´m sorry to hear that, try replacing the star_num in the lights function with this: start_num = round((int(position) - 1) * app.segment_size). Did you run the code from Scrach, or did you run the code with your existing db files?

**Comment by FireMarshmellow** [comment]
Yes I used my database I'll try it with a new one now.

**Comment by FireMarshmellow** [comment]
Never mind it works I'm the stupid one, I copied and pasted the ip Address with http://
However I did find a different problem https://youtube.com/shorts/rvderD2Meis?feature=share

**Comment by JustReit** [comment]
> Never mind it works I'm the stupid one, I copied and pasted the ip Address with http:// However I did find a different problem https://youtube.com/shorts/rvderD2Meis?feature=share

Regarding the first "issue" with the LEDs not turning off, it's meant to be that way, that's also one reason why I added the LED controls. I did that so the requests don't pile up and overwrite each other. Regarding the second issue: could you print the request which is sent to wled with following line in the lights function: print(pulsate_data)
so I can see if I find what the issue is? Thank you for the video :D

**Comment by JustReit** [comment]
> Never mind it works I'm the stupid one, I copied and pasted the ip Address with http:// However I did find a different problem https://youtube.com/shorts/rvderD2Meis?feature=share

I tried it out with multiple esps but they work exactly as intended.....

**Comment by FireMarshmellow** [comment]
So I restarted from scratch deleted the databases I still get the same issue,
I did get a print out of the request I trimmed it down to the only bits that are different.

Working as intended On the first ESP
{'on': True, 'bri': 255, 'transition': 0, 'mainseg': 0, 'seg': [{'id': 0, 'start': 20, 'stop': 25,

The second ESP all lights come on 
{'on': True, 'bri': 255, 'transition': 0, 'mainseg': 0, 'seg': [{'id': 0, 'start': 258, 'stop': 264, '

esp.db
1,192.168.1.150,25,5
2,192.168.1.179,60,6

**Comment by JustReit** [comment]
> So I restarted from scratch deleted the databases I still get the same issue, I did get a print out of the request I trimmed it down to the only bits that are different.
> 
> Working as intended On the first ESP {'on': True, 'bri': 255, 'transition': 0, 'mainseg': 0, 'seg': [{'id': 0, 'start': 20, 'stop': 25,
> 
> The second ESP all lights come on {'on': True, 'bri': 255, 'transition': 0, 'mainseg': 0, 'seg': [{'id': 0, 'start': 258, 'stop': 264, '
> 
> esp.db 1,192.168.1.150,25,5 2,192.168.1.179,60,6

Looks fine to me, it´s probably a problem with wled syncing all your leds, can you try resetting your wled and see if the problem still pops up. If you want we can solve the problem through discord.

**Comment by FireMarshmellow** [comment]
Sure I'll be in the general channel

**Comment by JustReit** [comment]
> Sure I'll be in the general channel

I´m sadly not in your discord channel, but you can add me if you want and we´ll figure out the problem:  nosescope

**Comment by FireMarshmellow** [comment]
https://discord.gg/raYDcSEp

**Pull request closed without merging**
