### PR TITLE
Modified code to use a sqlite DB instead of csv

### PR DESCRIPTION
**Pull request by nikpcenicni**
Modified app.py to use an sqlite DB instead of using the CSV to allow for larger databases and reliability.

### CODE REVIEW

**Comment by nikpcenicni** [comment]
Changed the styling to use tailwind css to allow for easier styling and responsiveness. Added a quantity system to the DB to allow for tracking, and organization. Quantities can be quickly updated through the added add and subtract buttons on the item card.
Screen Shot 2023-04-18 at 2 13 06 AM
Screen Shot 2023-04-18 at 2 12 52 AM
Screen Shot 2023-04-18 at 2 12 25 AM

**Comment by FireMarshmellow** [comment]
This is some really cool work thank you for taking the time, I only have one note. I would prefer the Add item form to drop down instead of over laying.

**Comment by nikpcenicni** [comment]
I will fix it after I’m done work today.

**Comment by FireMarshmellow** [comment]
Honestly I love everything you've done it is beautiful, cannot thank you enough for volunteering your time.

**Comment by Callsign-Carrot** [comment]
When editing an item, if you hit cancel on every prompt it will display the item as null. After some finicking with it (without refreshing) I tried to delete the null item and it locked the database requiring me to restart it. I haven't replicated the database locking yet. I assume it's because I tried to modify it too fast. I might have tried to add something after deleting the null item. As long as you don't lock the database, refreshing the page resolves the issue.
image
image

**Comment by FireMarshmellow** [comment]
@Callsign-Carrot yeah I'm kind of aware of this issue, it happens on the CSV version as well. There's a couple things I can do, option one I ignore it, option two I fix it, option three I get rid of the cancel button, 🤣🤣

**Comment by FireMarshmellow** [comment]
@nikpcenicni I hope you don't mind I took the liberty of making the changes myself, I tested everything it should work fine. But if you notice anything wrong let me know

**Pull request merged**
